export const bankOptions = [
  "Access Bank",
  "Guaranty Trust Bank (GTBank)",
  "United Bank for Africa (UBA)",
  "Zenith Bank",
  "First Bank of Nigeria",
  "Fidelity Bank",
  "Union Bank",
  "Sterling Bank",
  "Stanbic IBTC Bank",
  "Polaris Bank",
  "Wema Bank",
  "Ecobank",
  "Keystone Bank",
  "First City Monument Bank (FCMB)",
  "Heritage Bank",
  "Unity Bank",
  "Providus Bank",
  "Kuda Bank",
  "Opay",
  "PalmPay",
  "Moniepoint",
];
